#!/usr/bin/env bash
# Reset cloud demo state to a clean baseline before a presentation.
#
# Wipes anything created by exercising the buyback flow:
#   - return_requests, return_request_events, condition_assessments, assessment_photos
#   - refurb_listings, donation_records, trade_in_credits
#   - store_credit_ledger entries that came from the demo flow
#   - shopify_stub_products, shopify_stub_discount_codes, shopify_stub_log
# Resets owned_units back to 'owned' so My Products lights up the same way every
# time. Leaves accounts, products, child_profiles, ngo_partners, orders, and
# order_line_items intact (the immutable seed data).
#
# Usage:
#   set -a; source .cloud-admin-secret; set +a
#   bash scripts/reset-demo.sh

set -euo pipefail

if [ -z "${GENERATED_SECRET:-}" ]; then
  echo "Admin secret not set. Run: set -a; source .cloud-admin-secret; set +a" >&2
  exit 1
fi

URL='https://ntytiuebfzzodrotraun.hasura.ap-south-1.nhost.run/v2/query'
PROXY='--socks5-hostname 127.0.0.1:1080'

run_sql() {
  local sql="$1"
  local payload
  payload=$(jq -Rs --arg sql "$sql" '{type:"run_sql", args:{sql:$sql, cascade:true}}' <<<'')
  curl -sS $PROXY -X POST "$URL" \
    -H "Content-Type: application/json" \
    -H "x-hasura-admin-secret: $GENERATED_SECRET" \
    -d "$payload" | jq -r '.result_type // .error // "?"'
}

echo "==> Resetting demo state on cloud Hasura"

run_sql "
  -- Wipe anything generated by the buyback flow.
  delete from shopify_stub_log;
  delete from shopify_stub_discount_codes;
  delete from shopify_stub_products;
  delete from discount_codes;
  delete from credit_transfers;
  delete from store_credit_ledger;
  delete from trade_in_credits;
  delete from donation_records;
  delete from refurb_listings;
  delete from assessment_photos;
  delete from condition_assessments;
  delete from return_request_events;
  delete from return_requests;

  -- Re-arm owned_units so they all show as 'owned' again.
  update owned_units set status = 'owned', returned_at = null;
"

echo "==> Done. Demo state is clean."
